
-- 1. CRIAÇÃO DA TABELA (Se já rodou, não precisa rodar de novo)
create table if not exists products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  category text not null,
  price numeric not null,
  image_url text,
  description text,
  stock integer default 1,
  size text,
  payment_link text,
  pix_key text,
  aggressiveness text,
  color text,
  brand text,
  filtration_type text,
  capacity text
);

-- 2. CONFIGURAÇÃO DO STORAGE (IMPORTANTE: RODE ISSO NO SQL EDITOR)

-- Cria o bucket 'products' se não existir
insert into storage.buckets (id, name, public)
values ('products', 'products', true)
on conflict (id) do nothing;

-- Remove políticas antigas para evitar conflito
drop policy if exists "Public Access" on storage.objects;
drop policy if exists "Authenticated Insert" on storage.objects;

-- Permite que QUALQUER pessoa veja as imagens (necessário para o site funcionar)
create policy "Public Access"
on storage.objects for select
using ( bucket_id = 'products' );

-- Permite upload (como você está usando a service_role key, isso funcionará direto, 
-- mas deixamos a política criada para boas práticas)
create policy "Allow Uploads"
on storage.objects for insert
with check ( bucket_id = 'products' );
