
-- ==============================================================================
-- SETUP DO BANCO DE DADOS CANAÃ FISH
-- Copie e cole este código no SQL Editor do Supabase e clique em "Run".
-- ==============================================================================

-- 1. CRIAÇÃO DA TABELA DE PRODUTOS
-- Verifica se a tabela já existe para evitar erros, ou recria se necessário.
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price NUMERIC NOT NULL,
  image_url TEXT,
  description TEXT,
  stock INTEGER DEFAULT 1,
  
  -- Campos específicos mapeados do seu types.ts e App.tsx
  size TEXT,
  payment_link TEXT,
  pix_key TEXT,
  aggressiveness TEXT,
  color TEXT,
  brand TEXT,
  filtration_type TEXT,
  capacity TEXT
);

-- 2. HABILITAR ROW LEVEL SECURITY (RLS)
-- Isso é necessário para que as políticas de acesso funcionem.
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- 3. POLÍTICAS DE ACESSO (PERMISSÕES)

-- Remover políticas antigas se existirem para evitar conflitos
DROP POLICY IF EXISTS "Permitir Leitura Publica" ON public.products;
DROP POLICY IF EXISTS "Permitir Escrita Publica" ON public.products;

-- Política 1: Todo mundo pode VER os produtos (Leitura Pública)
CREATE POLICY "Permitir Leitura Publica"
ON public.products FOR SELECT
USING (true);

-- Política 2: Permitir Insert/Update/Delete
-- NOTA: Como você está usando autenticação local no React ('canaa123') e não Auth do Supabase,
-- estamos liberando a escrita pública na API. 
-- *Segurança*: No seu código (supabaseClient.ts), você está usando a 'service_role' key (que começa com eyJ...),
-- o que já ignora essas regras. Se você mudar para a 'anon' key no futuro, esta regra permitirá que o Admin funcione.
CREATE POLICY "Permitir Escrita Publica"
ON public.products FOR ALL
USING (true)
WITH CHECK (true);

-- 4. CONFIGURAÇÃO DO STORAGE (BUCKET DE IMAGENS)

-- Cria o bucket 'products' se ele não existir
INSERT INTO storage.buckets (id, name, public)
VALUES ('products', 'products', true)
ON CONFLICT (id) DO NOTHING;

-- Políticas de acesso ao Storage
DROP POLICY IF EXISTS "Imagens Publicas" ON storage.objects;
DROP POLICY IF EXISTS "Upload de Imagens" ON storage.objects;
DROP POLICY IF EXISTS "Deletar Imagens" ON storage.objects;

-- Qualquer um pode ver as imagens
CREATE POLICY "Imagens Publicas"
ON storage.objects FOR SELECT
USING ( bucket_id = 'products' );

-- Permitir upload de imagens
CREATE POLICY "Upload de Imagens"
ON storage.objects FOR INSERT
WITH CHECK ( bucket_id = 'products' );

-- Permitir deletar/atualizar imagens
CREATE POLICY "Gerenciar Imagens"
ON storage.objects FOR UPDATE
USING ( bucket_id = 'products' );

CREATE POLICY "Deletar Imagens"
ON storage.objects FOR DELETE
USING ( bucket_id = 'products' );
