-- ==============================================================================
-- SETUP DO BANCO DE DADOS AQUARISMO PANUCCI
-- Copie e cole este código no SQL Editor do seu projeto Supabase e clique em "Run".
-- Projeto: ltnkqxfrtvnmsmllebkq
-- ==============================================================================

-- 1. CRIAÇÃO DA TABELA DE PRODUTOS
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price NUMERIC NOT NULL,
  image_url TEXT,
  description TEXT,
  stock INTEGER DEFAULT 1,
  
  -- Campos específicos de taxonomia/filtros
  size TEXT,
  payment_link TEXT,
  pix_key TEXT,
  aggressiveness TEXT,
  color TEXT,
  brand TEXT,
  filtration_type TEXT,
  capacity TEXT,
  ph TEXT,
  tags TEXT[],
  collections TEXT[]
);

-- 2. HABILITAR ROW LEVEL SECURITY (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- 3. POLÍTICAS DE ACESSO (PERMISSÕES)
DROP POLICY IF EXISTS "Permitir Leitura Publica" ON public.products;
DROP POLICY IF EXISTS "Permitir Escrita Publica" ON public.products;

-- Política 1: Todo mundo pode VER os produtos (Leitura Pública)
CREATE POLICY "Permitir Leitura Publica"
ON public.products FOR SELECT
USING (true);

-- Política 2: Permitir Insert/Update/Delete publicamente (para login custom)
CREATE POLICY "Permitir Escrita Publica"
ON public.products FOR ALL
USING (true)
WITH CHECK (true);

-- 4. CONFIGURAÇÃO DO STORAGE (BUCKET DE IMAGENS)
INSERT INTO storage.buckets (id, name, public)
VALUES ('products', 'products', true)
ON CONFLICT (id) DO NOTHING;

-- Políticas de acesso ao Storage
DROP POLICY IF EXISTS "Imagens Publicas" ON storage.objects;
DROP POLICY IF EXISTS "Upload de Imagens" ON storage.objects;
DROP POLICY IF EXISTS "Gerenciar Imagens" ON storage.objects;
DROP POLICY IF EXISTS "Deletar Imagens" ON storage.objects;

CREATE POLICY "Imagens Publicas"
ON storage.objects FOR SELECT
USING ( bucket_id = 'products' );

CREATE POLICY "Upload de Imagens"
ON storage.objects FOR INSERT
WITH CHECK ( bucket_id = 'products' );

CREATE POLICY "Gerenciar Imagens"
ON storage.objects FOR UPDATE
USING ( bucket_id = 'products' );

CREATE POLICY "Deletar Imagens"
ON storage.objects FOR DELETE
USING ( bucket_id = 'products' );

-- 5. DADOS DE EXEMPLO (SEMENTES / MOCK DATA)
-- Limpa a tabela para não duplicar caso rode duas vezes
TRUNCATE TABLE public.products RESTART IDENTITY;

INSERT INTO public.products (name, category, price, image_url, description, stock, size, aggressiveness, ph, pix_key)
VALUES 
(
  'Aruanã Prateada (Osteoglossum bicirrhosum)', 
  'Jumbos', 
  850.00, 
  'https://i.postimg.cc/brDgBVTJ/Logo-Panucci.png', 
  'Peixe majestoso da bacia amazônica. Possui escamas grandes e um nado elegante. Requer aquários de grande porte com tampas reforçadas, pois são excelentes saltadores.', 
  3, 
  '20cm - 25cm', 
  'Semi-agressivo', 
  '6.0 - 7.0',
  '11973828507'
),
(
  'Arraia Motoro (Potamotrygon motoro)', 
  'Primitivos', 
  1200.00, 
  'https://i.postimg.cc/brDgBVTJ/Logo-Panucci.png', 
  'Arraia de água doce muito resistente e ativa. Padrão de cores deslumbrante com ocelos marcantes. Necessita de substrato macio e excelente filtragem biológica.', 
  2, 
  'Disco 15cm', 
  'Pacífico', 
  '6.5 - 7.5',
  '11973828507'
),
(
  'Filtro Canister Premium 2000L/H', 
  'Equipamentos', 
  1450.00, 
  'https://i.postimg.cc/brDgBVTJ/Logo-Panucci.png', 
  'Filtro externo de alta performance com esterilizador UV integrado. Extremamente silencioso. Acompanha mídias biológicas de vidro sinterizado de brinde.', 
  5, 
  'N/A', 
  'N/A', 
  'N/A',
  '11973828507'
);
